name: check for broken links

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Markup Link Checker (mlc)
        uses: Wandalen/wretry.action@v1.3.0
        with:
          action: becheran/mlc@v0.16.2
          with: |
            args: --ignore-path "CHANGELOG.md"
          attempt_limit: 3
          attempt_delay: 2000