name: check for broken links

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Markup Link Checker (mlc)
        uses: becheran/mlc@v0.15.3
        with:
          args: --ignore-path "CHANGELOG.md"